# The C runtime linked into the exe: no VCRUNTIME140.dll, so qrec runs on a
# Windows without the Visual C++ Redistributable.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
